/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionsClientRouteImport } from './routes/positions.client'
import { Route as BorrowClientRouteImport } from './routes/borrow.client'
import { Route as AdminClientRouteImport } from './routes/admin.client'

const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsClientRoute = PositionsClientRouteImport.update({
  id: '/positions/client',
  path: '/positions/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowClientRoute = BorrowClientRouteImport.update({
  id: '/borrow/client',
  path: '/borrow/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientRoute = AdminClientRouteImport.update({
  id: '/admin/client',
  path: '/admin/client',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supply': typeof SupplyRoute
  '/admin/client': typeof AdminClientRoute
  '/borrow/client': typeof BorrowClientRoute
  '/positions/client': typeof PositionsClientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/supply': typeof SupplyRoute
  '/admin/client': typeof AdminClientRoute
  '/borrow/client': typeof BorrowClientRoute
  '/positions/client': typeof PositionsClientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/supply': typeof SupplyRoute
  '/admin/client': typeof AdminClientRoute
  '/borrow/client': typeof BorrowClientRoute
  '/positions/client': typeof PositionsClientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/supply'
    | '/admin/client'
    | '/borrow/client'
    | '/positions/client'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/supply' | '/admin/client' | '/borrow/client' | '/positions/client'
  id:
    | '__root__'
    | '/'
    | '/supply'
    | '/admin/client'
    | '/borrow/client'
    | '/positions/client'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupplyRoute: typeof SupplyRoute
  AdminClientRoute: typeof AdminClientRoute
  BorrowClientRoute: typeof BorrowClientRoute
  PositionsClientRoute: typeof PositionsClientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/client': {
      id: '/positions/client'
      path: '/positions/client'
      fullPath: '/positions/client'
      preLoaderRoute: typeof PositionsClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow/client': {
      id: '/borrow/client'
      path: '/borrow/client'
      fullPath: '/borrow/client'
      preLoaderRoute: typeof BorrowClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/client': {
      id: '/admin/client'
      path: '/admin/client'
      fullPath: '/admin/client'
      preLoaderRoute: typeof AdminClientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupplyRoute: SupplyRoute,
  AdminClientRoute: AdminClientRoute,
  BorrowClientRoute: BorrowClientRoute,
  PositionsClientRoute: PositionsClientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
